### ISSUE TITLE
Pull Facilities by State (locale)

### ISSUE THREAD

**Issue by johnfedwards** [department-of-veterans-affairs/vets-api-clients#36]
## APIs Affected

VA Facilities API

## Explanation Feature

User would supply the 2 letter abbreviation for a state or locale and returned would be a list of the facilities in that locale.

## Value Provided by Feature

Perhaps just return summary data (ID, Facility Name, and Facility Type) so this could be used to populate a drop-down without the overhead of returning all the data for each facility.

## Acceptance Criteria

The ability for every facility to be returned given it matched the state/locale provided in the call.

**Comment by Eallan919** [comment]
Hi @johnfedwards Thank you for your submission! We pulled your request and will keep you updated as we progress!

**Comment by ryanlink** [comment]
Hi @johnfedwards - thanks for your patience on this.  We are still working on it, contingent on some internal VA decisions regarding the Facilities API.  It's in the queue!

Cheers,

Ryan Link
Customer Success Manager | Oddball.io
Support Portal for VA API Team
developer.va.gov

**Comment by ryanlink** [comment]
Hi @johnfedwards - This has been resolved, and the fix was deployed in this [pull request](https://github.com/department-of-veterans-affairs/vets-api/pull/2992).  Please have a look at the [Release Notes](https://developer.va.gov/release-notes/facilities) for more info.

Thanks,

Ryan Link
Customer Success Manager, Oddball
API Support Lead, Lighthouse | VA API Program

Visit developer.va.gov for more on the VA API Program
